server:
  port: 8084
aws:
  accessKeyId: AKIA3NM5FFKYTI6FZCBW
  secretKey: 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
  dynamodb:
    endpoint: dynamodb.eu-central-1.amazonaws.com
spring:
  application:
    name: contact-service
  data:
    dynamodb:
      entity2ddl:
        auto: create-only