server:
  port: 8083
spring:
  application:
    name: sms-message-service
#  datasource:
#    password: password
#    url: jdbc:postgresql://localhost:5432/
#    username: admin
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true